name: Auto Release by Pull Request

on:
  push:
    branches:
      - <TARGET_BRANCH>

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - name: Auto Release
        id: auto-release
        uses: akfmdl/github-actions-workflows/actions/auto-release-custom-versioning@test
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-branches: '["test"]'
          version-py-path: 'version.py'  # 선택사항: version.py 파일 경로

      - name: Check outputs
        run: |
          echo "new-release-published: ${{ steps.auto-release.outputs.new-release-published }}"
          echo "new-release-version: ${{ steps.auto-release.outputs.new-release-version }}"
          echo "new-release-git-tag: ${{ steps.auto-release.outputs.new-release-git-tag }}"
          echo "new-release-git-head: ${{ steps.auto-release.outputs.new-release-git-head }}"

      - name: Post-release notification
        if: steps.auto-release.outputs.new-release-published == 'true'
        run: |
          echo "🎉 새로운 릴리즈가 생성되었습니다!"
          echo "버전: ${{ steps.auto-release.outputs.new-release-version }}"
          echo "태그: ${{ steps.auto-release.outputs.new-release-git-tag }}"
          echo "SHA: ${{ steps.auto-release.outputs.new-release-git-head }}"