name: Auto Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - name: Auto Release
        uses: akfmdl/github-actions-workflows/actions/auto-release@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-branches: '["main"]'
          # dry-run: true # 테스트 모드

      - name: Post-release notification
        if: steps.release.outputs.new-release-published == 'true'
        run: |
          echo "🎉 새로운 릴리즈가 생성되었습니다!"
          echo "버전: ${{ steps.release.outputs.new-release-version }}"
          echo "태그: ${{ steps.release.outputs.new-release-git-tag }}"
          echo "SHA: ${{ steps.release.outputs.new-release-git-head }}" 